apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-source-workspace
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
