# Falco - Container Runtime Security
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  labels:
    app.kubernetes.io/component: runtime-security
    app.kubernetes.io/part-of: security
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: security
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: "7.2.1"
      helm:
        valueFiles:
          - $values/charts/falco/falco-values.yaml
    - repoURL: https://github.com/smii/k3sdevlab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
